import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {initialize,council,finishCouncil} from './project.mjs';
import {read,atomic,fingerprint} from './engine.mjs';
import {runCouncilReview,councilReplies} from './council-worker.mjs';
function setup(t,script){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'council-worker-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const root=initialize(dir,'test-series','test'),file=path.join(root,'system/series.json'),config=read(file);for(const role of ['socrates','machiavelli','keynes','editor','continuity'])config.workers[role]={command:process.execPath,args:['-e',script],timeout_ms:5000};atomic(file,config);return {root,meeting:council(root,'transport test only')};}
const echo="let s='';process.stdin.on('data',c=>s+=c);process.stdin.on('end',()=>{const r=JSON.parse(s);console.log(JSON.stringify({request_id:r.request_id,series_id:r.series_id,base:r.base,role:r.role,output:'MOCK '+r.role}));});";
test('five external processes answer original requests without completing meeting or changing canon',async t=>{const {root,meeting}=setup(t,echo),before=fingerprint(root);for(const req of meeting.requests)assert.equal((await runCouncilReview(root,meeting.id,req.role)).status,'received');const collected=councilReplies(root,meeting.id);assert.equal(collected.ready_for_resolution,true);assert.equal(collected.replies.length,5);assert.equal((await runCouncilReview(root,meeting.id,'socrates')).status,'already_received');assert.equal(fs.readdirSync(path.join(root,'system/worker-runs')).length,5);assert.equal(read(path.join(root,'system/councils',meeting.id+'.json')).status,'awaiting_reviews');assert.equal(fingerprint(root),before);const done=finishCouncil(root,meeting.id,collected.replies,{execution_mode:'external_workers',summary:'Mock transport review only',objections:[],pending:['real AI test']});assert.equal(done.status,'reviewed_proposal');});
test('failure retains unconfirmed attempt and refuses automatic rerun',async t=>{const {root,meeting}=setup(t,"process.stdin.resume();process.stdin.on('end',()=>console.log('invalid'));");await assert.rejects(runCouncilReview(root,meeting.id,'socrates'),/not confirmed/);await assert.rejects(runCouncilReview(root,meeting.id,'socrates'),/automatic retry refused/);assert.equal(councilReplies(root,meeting.id).pending.length,5);});
test('stale and foreign meetings are rejected before starting workers',async t=>{const {root,meeting}=setup(t,echo),file=path.join(root,'system/councils',meeting.id+'.json');for(const changed of [{...meeting,series_id:'foreign'},{...meeting,base:'old'}]){atomic(file,changed);await assert.rejects(runCouncilReview(root,meeting.id,'socrates'),/wrong series or stale/);}assert.ok(!fs.existsSync(path.join(root,'system/worker-runs')));});
