import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {progress} from './progress.mjs';
import http from 'node:http';
const dir=path.dirname(fileURLToPath(import.meta.url));
const d=JSON.parse(fs.readFileSync(path.join(dir,'development-status.json'),'utf8'));
const p=progress(path.join(dir,'../amelia'));
const c=p.chapters.find(x=>x.active&&Number(x.chapter)===1);
const escape=x=>String(x).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const labels={verified:'検証済み',partial:'一部完了',pending:'これから'};
const cards=d.items.map(i=>`<article data-status="${i.status}"><div class="tag ${i.status}">${labels[i.status]}</div><h3>${escape(i.name)}</h3><p>${escape(i.detail)}</p><a href="https://github.com/teufelszeug-wq/Codex001/blob/main/writing-system/${encodeURI(i.evidence)}" target="_blank" rel="noreferrer">根拠・実装を見る ↗</a></article>`).join('');
const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>小説制作システム｜開発進捗</title>
<style>
:root{font-family:system-ui,"Yu Gothic",sans-serif;color:#22352f;background:#f4f5f0}*{box-sizing:border-box}body{margin:0}main{max-width:1180px;margin:auto;padding:42px 28px}a{color:#206851}header{display:flex;justify-content:space-between;gap:20px;align-items:center}.eyebrow{font-size:13px;letter-spacing:.14em;color:#64756b}h1{font-size:32px;margin:12px 0}h2{font-size:21px;margin:0 0 20px}h3{font-size:17px;line-height:1.6;margin:12px 0}p{line-height:1.8;color:#57645d}nav{display:flex;gap:18px;font-size:14px}.hero{background:#193f33;color:white;border-radius:20px;padding:28px 32px;margin:30px 0}.hero p{color:#d6e5db;margin-bottom:0}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0}.stat{background:white;border:1px solid #dce1d8;border-radius:14px;padding:20px}.stat strong{display:block;font-size:32px;margin:8px 0}.stat small{color:#657368}.controls{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}button{font:inherit;border:1px solid #cbd5cb;background:transparent;border-radius:24px;padding:9px 18px;cursor:pointer}button[aria-pressed=true]{background:#234f3c;color:white;border-color:#234f3c}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}article{background:white;border:1px solid #dce1d8;border-radius:14px;padding:22px;display:flex;flex-direction:column}article p{font-size:14px;margin-top:0;flex:1}article a{font-size:12px}.tag{font-size:12px;border-radius:6px;padding:5px 9px;align-self:flex-start}.verified{background:#e0eee3;color:#286641}.partial{background:#fff0cd;color:#866312}.pending{background:#edf0f2;color:#5a6771}.bottom{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:28px}.panel{padding:26px;background:#fff;border:1px solid #dce1d8;border-radius:14px}li{line-height:1.9;margin-bottom:8px;font-size:14px}.note{font-size:12px;color:#748076;margin-top:20px}[hidden]{display:none}footer{margin:28px 0;font-size:12px;color:#748076}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}header{display:block}nav{margin-top:18px}.bottom{grid-template-columns:1fr}}@media(max-width:520px){main{padding:24px 16px}.grid,.stats{grid-template-columns:1fr}h1{font-size:25px}.hero{padding:24px}}
</style><main><header><div><div class="eyebrow">WRITING SYSTEM / DEVELOPMENT</div><h1>小説制作システムの開発進捗</h1><span>記録更新：${escape(d.updated)}</span></div><nav><a href="https://app.notion.com/p/3de76efc402981fb81a6cf238c227903" target="_blank" rel="noreferrer">Notion台帳 ↗</a><a href="https://github.com/teufelszeug-wq/Codex001/tree/main/writing-system" target="_blank" rel="noreferrer">GitHub ↗</a></nav></header>
<section class="hero"><div class="eyebrow" style="color:#b3d2bd">現在の段階</div><h2 style="margin:12px 0">${escape(d.phase)}</h2><p>企画 → 世界設定 → 会議 → 執筆 → 改稿 → 保存を、会話と外部AIの両方式で使える環境へ。</p><p style="font-size:13px">${escape(d.tests)}</p></section>
<div class="stats">${Object.entries(labels).map(([k,v])=>`<div class="stat">${v}<strong>${d.items.filter(x=>x.status===k).length}<span style="font-size:14px"> 項目</span></strong><small>${k==='verified'?'記載した範囲の動作を検証':k==='partial'?'実装・接続・照合に残件あり':'必要な開発・検証が残っている'}</small></div>`).join('')}</div><p class="note">項目数は完成率ではありません。規模の異なる機能を同じ重さで計算せず、検証できた範囲を表示しています。</p>
<h2 style="margin-top:32px">機能ごとの状況</h2><div class="controls" aria-label="進捗の絞り込み"><button data-filter="all" aria-pressed="true">すべて</button>${Object.entries(labels).map(([k,v])=>`<button data-filter="${k}" aria-pressed="false">${v}</button>`).join('')}</div><div class="grid">${cards}</div>
<div class="bottom"><section class="panel"><h2>次に進めること</h2><ol>${d.next.map(x=>`<li>${escape(x)}</li>`).join('')}</ol></section><section class="panel"><h2>最近の更新</h2><ul>${d.history.map(x=>`<li>${escape(x)}</li>`).join('')}</ul></section><section class="panel"><h2>アメリアの執筆状況</h2><div class="tag partial">C01-S07で停止中</div><p>現行C版・第1章の登録原稿：<strong>${c.current_text_chars.toLocaleString()}字</strong><br>仮稿：${c.draft_chars.toLocaleString()}字 ／ 確定稿：${c.approved_chars.toLocaleString()}字</p><p>最低目標10万字。旧A・B版は加算していません。未登録・未取得の本文を「未執筆」と断定しません。</p><small>原稿ファイル全体の改行を除く文字数（見出し・空白を含む）。本文は再開していません。</small></section><section class="panel"><h2>完了までの条件</h2><p>実AIを接続したレビュー、2作品以上の独立運用、保存と復旧の確認が必要です。全体完成時は三人の知性を含む会議で不足を検討します。</p><a href="https://github.com/teufelszeug-wq/Codex001/commit/${escape(d.last_verified_commit)}">直近の確認済み保存版 ↗</a></section></div>
<footer>この画面は更新記録から生成したスナップショットです。常時監視ではありません。開発の進行時に記録と画面を再生成します。生成日時：${escape(new Date().toISOString())}</footer></main><script>document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('[data-status]').forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.status!==b.dataset.filter);}));</script></html>`;
fs.writeFileSync(path.join(dir,'開発進捗.html'),html);
console.log(JSON.stringify({file:path.join(dir,'開発進捗.html'),items:d.items.length,amelia:c.current_text_chars}));
if(process.argv.includes('--serve'))http.createServer((req,res)=>{
  if(req.url!=='/'){res.writeHead(404);res.end();return;}
  res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});
  res.end(fs.readFileSync(path.join(dir,'開発進捗.html')));
}).listen(12901,'127.0.0.1',()=>console.log('http://127.0.0.1:12901'));
