import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {initialize,finishCouncil} from './project.mjs';
import {read,atomic,inside,fingerprint,request} from './engine.mjs';
import {manuscriptForReview,manuscriptCouncil} from './manuscript-review.mjs';
import {runCouncilReview,councilReplies} from './council-worker.mjs';
import {planningHistory} from './planning-history.mjs';
import {planningServer} from './planning-server.mjs';
import crypto from 'node:crypto';
import vm from 'node:vm';
function fixture(t){const w=fs.mkdtempSync(path.join(os.tmpdir(),'novel-review-'));t.after(()=>fs.rmSync(w,{recursive:true,force:true}));const root=initialize(w,'test-novel','Test');const c=read(inside(root,'system/series.json'));c.pov_character='hero';atomic(inside(root,'system/series.json'),c);const s=read(inside(root,'state.json'));s.cards=[{id:'hero',type:'character',name:'Hero',status:'confirmed',source:'test',knows:['a known fact']},{id:'secret',type:'fact',status:'confirmed',source:'test',value:'AUTHOR_SECRET'}];s.current_scene='S1';s.scene_log=[{id:'S1',path:'manuscript/s1.md',status:'draft',source:'test'}];atomic(inside(root,'state.json'),s);fs.writeFileSync(inside(root,'manuscript/s1.md'),'# Test\nA manuscript with FUTURE_SECRET.\n');return root;}
function input(root){const i={series_id:'test-novel',scene_id:'S1',base:fingerprint(root)};return {...i,manuscript_sha256:manuscriptForReview(root,i).sha256,agenda:'AGENDA_SECRET',workflow:'hybrid'};}
test('HTTP manuscript selection and confirmed council creation are read-only then idempotent and stale-safe',async t=>{
  const root=fixture(t),before=fingerprint(root),server=planningServer(root);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));});const url='http://127.0.0.1:'+server.address().port,ctx=await(await fetch(url+'/api/init')).json();
  const post=(route,data,headers={})=>fetch(url+route,{method:'POST',headers:{'Content-Type':'application/json','X-Planning-Token':ctx.token,...headers},body:JSON.stringify(data)});
  assert.equal((await fetch(url+'/api/manuscripts')).status,403);const list=await(await fetch(url+'/api/manuscripts',{headers:{'X-Planning-Token':ctx.token}})).json();assert.equal(list.scenes[0].id,'S1');assert.equal(list.paused,true);
  const readInput={series_id:ctx.series_id,scene_id:'S1',base:ctx.base};assert.equal((await post('/api/read-manuscript',readInput,{'Origin':'https://foreign.example'})).status,403);assert.equal((await post('/api/read-manuscript',{...readInput,series_id:'foreign'})).status,400);const source=await(await post('/api/read-manuscript',readInput)).json();assert.equal(source.text,fs.readFileSync(inside(root,'manuscript/s1.md'),'utf8'));assert.ok(!fs.existsSync(inside(root,'system/operations')));
  const payload={operation_id:crypto.randomUUID(),base:ctx.base,confirmed:true,review:{...readInput,manuscript_sha256:source.sha256,agenda:'Review this scene',workflow:'conversation'}};
  for(const bad of [{...payload,confirmed:false},{...payload,review:{...payload.review,manuscript_sha256:'bad'}},{...payload,review:{...payload.review,agenda:''}}]){assert.equal((await post('/api/manuscript-council',bad)).status,400);assert.ok(!fs.existsSync(inside(root,'system/operations')));}
  const response=await post('/api/manuscript-council',payload);assert.equal(response.status,200);const m=await response.json();assert.equal(m.roles.length,6);assert.equal(m.execution_mode,'requests_only');assert.equal((await(await post('/api/manuscript-council',payload)).json()).id,m.id);assert.equal(fs.readdirSync(inside(root,'system/councils')).length,1);assert.equal(fingerprint(root),before);
  const page=await(await fetch(url+'/manuscript-review')).text();new vm.Script(page.match(/<script>([\s\S]*?)<\/script>/)[1]);assert.ok(page.includes("$('body').textContent=source.text"));assert.ok((await(await fetch(url+'/')).text()).includes('/manuscript-review'));
  fs.appendFileSync(inside(root,'manuscript/s1.md'),'new content');assert.equal((await post('/api/manuscript-council',{...payload,operation_id:crypto.randomUUID()})).status,400);assert.equal(fs.readdirSync(inside(root,'system/councils')).length,1);
});
test('history retains reviewed original while flagging stale basis and hides damaged snapshot',t=>{const r=fixture(t),m=manuscriptCouncil(r,input(r)),before=fingerprint(r);let h=planningHistory(r);assert.equal(h.councils[0].reviews.length,6);assert.equal(h.councils[0].manuscript.text,m.manuscript.text);assert.deepEqual(h.issues,[]);assert.equal(fingerprint(r),before);fs.appendFileSync(inside(r,'manuscript/s1.md'),'new text');h=planningHistory(r);assert.equal(h.councils[0].stale,true);assert.equal(h.councils[0].manuscript.text,m.manuscript.text);m.manuscript.text='DAMAGED SNAPSHOT';atomic(inside(r,'system/councils/'+m.id+'.json'),m);h=planningHistory(r);assert.equal(h.councils.length,0);assert.ok(h.issues.length);assert.ok(!JSON.stringify(h).includes('DAMAGED SNAPSHOT'));});
test('HTTP saves six-role drafts and resolutions and returns manuscript snapshot without changing canon',async t=>{const r=fixture(t),m=manuscriptCouncil(r,input(r)),before=fingerprint(r),server=planningServer(r);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));});const url='http://127.0.0.1:'+server.address().port,ctx=await(await fetch(url+'/api/init')).json();const post=(route,payload)=>fetch(url+route,{method:'POST',headers:{'Content-Type':'application/json','X-Planning-Token':ctx.token},body:JSON.stringify(payload)});const payload={operation_id:crypto.randomUUID(),base:ctx.base,meeting_id:m.id,reviews:m.requests.map(q=>({role:q.role,output:''})),resolution:{execution_mode:'',summary:'',objections:[],pending:[]}};const d=await post('/api/save-council-draft',payload);assert.equal(d.status,200);const saved=await d.json();assert.equal((await(await post('/api/save-council-draft',payload)).json()).id,saved.id);let h=planningHistory(r);assert.equal(h.drafts.length,1);assert.equal(h.drafts[0].payload.reviews.length,6);assert.equal(h.councils[0].status,'awaiting_reviews');assert.equal((await post('/api/finish-council',payload)).status,400);const done={...payload,operation_id:crypto.randomUUID(),reviews:payload.reviews.map(q=>({...q,output:'Review'})),resolution:{execution_mode:'conversation_single_assistant',summary:'Proposal',objections:[],pending:['User decision']}};assert.equal((await post('/api/finish-council',done)).status,200);assert.equal((await post('/api/finish-council',done)).status,200);assert.equal((await fetch(url+'/api/history')).status,403);h=await(await fetch(url+'/api/history',{headers:{'X-Planning-Token':ctx.token}})).json();assert.equal(h.councils[0].collected_count,6);assert.equal(h.councils[0].manuscript.sha256,m.manuscript.sha256);assert.equal(h.councils[0].resolution.summary,'Proposal');assert.equal(fingerprint(r),before);const html=await(await fetch(url+'/')).text();new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1]);assert.ok(html.includes('meeting.reviews.length'));assert.ok(html.includes('body.textContent=meeting.manuscript.text'));});
test('read and six-perspective review preserve paused canon and isolate character knowledge',t=>{const r=fixture(t),i=input(r),before=fingerprint(r),m=manuscriptCouncil(r,i);assert.equal(m.requests.length,6);assert.equal(m.kind,'manuscript_review');assert.equal(m.execution_mode,'requests_only');assert.equal(m.manuscript.text,fs.readFileSync(inside(r,'manuscript/s1.md'),'utf8'));const pov=m.requests.find(x=>x.role==='character');const serialized=JSON.stringify(pov);for(const secret of ['AUTHOR_SECRET','FUTURE_SECRET','AGENDA_SECRET'])assert.ok(!serialized.includes(secret));assert.ok(serialized.includes('a known fact'));assert.ok(m.requests.find(x=>x.role==='editor').context.manuscript.text.includes('FUTURE_SECRET'));assert.equal(fingerprint(r),before);assert.throws(()=>request(r,'writer','write'),/paused/);});
test('review requires correct series scene exact text workflow and configured character',t=>{const r=fixture(t),i=input(r);for(const edit of [{series_id:'other'},{scene_id:'missing'},{base:'old'},{manuscript_sha256:'wrong'},{agenda:''},{workflow:'unknown'}])assert.throws(()=>manuscriptCouncil(r,{...i,...edit}));const c=read(inside(r,'system/series.json'));c.pov_character=null;atomic(inside(r,'system/series.json'),c);assert.throws(()=>manuscriptCouncil(r,input(r)),/POV/);assert.equal(fs.existsSync(inside(r,'system/councils')),false);});
test('all replies remain proposals and manuscript changes invalidate older review',t=>{const r=fixture(t),m=manuscriptCouncil(r,input(r)),base=fingerprint(r),replies=m.requests.map(q=>({...q,output:'Review only'})),resolution={execution_mode:'conversation_single_assistant',summary:'Consider changes',objections:[],pending:['User decision']};assert.throws(()=>finishCouncil(r,m.id,replies.slice(1),resolution));assert.equal(finishCouncil(r,m.id,replies,resolution).status,'reviewed_proposal');assert.equal(finishCouncil(r,m.id,replies,resolution).status,'reviewed_proposal');assert.equal(fingerprint(r),base);fs.appendFileSync(inside(r,'manuscript/s1.md'),'Later edit');assert.throws(()=>finishCouncil(r,m.id,replies,resolution),/stale/);assert.equal(read(inside(r,'system/control.json')).manuscript_generation_enabled,false);});
test('six mock workers collect original review requests without exposing author text to character',async t=>{const r=fixture(t),c=read(inside(r,'system/series.json'));const script="let s='';process.stdin.on('data',x=>s+=x);process.stdin.on('end',()=>{const q=JSON.parse(s);if(q.role==='character'&&/AUTHOR_SECRET|FUTURE_SECRET|AGENDA_SECRET/.test(s))process.exit(2);console.log(JSON.stringify({request_id:q.request_id,series_id:q.series_id,base:q.base,role:q.role,output:'MOCK review'}));});";for(const role of ['socrates','machiavelli','keynes','editor','continuity','character'])c.workers[role]={command:process.execPath,args:['-e',script],timeout_ms:5000};atomic(inside(r,'system/series.json'),c);const m=manuscriptCouncil(r,input(r)),base=fingerprint(r);for(const q of m.requests)assert.equal((await runCouncilReview(r,m.id,q.role)).status,'received');const collected=councilReplies(r,m.id);assert.equal(collected.replies.length,6);assert.equal(collected.ready_for_resolution,true);assert.equal((await runCouncilReview(r,m.id,'character')).status,'already_received');assert.equal(finishCouncil(r,m.id,collected.replies,{execution_mode:'external_workers',summary:'Mock only',objections:[],pending:['Real AI untested']}).status,'reviewed_proposal');assert.equal(fingerprint(r),base);});
