import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {initialize,finishCouncil} from './project.mjs';
import {read,atomic,inside,fingerprint,request} from './engine.mjs';
import {manuscriptForReview,manuscriptCouncil} from './manuscript-review.mjs';
import {runCouncilReview,councilReplies} from './council-worker.mjs';
function fixture(t){const w=fs.mkdtempSync(path.join(os.tmpdir(),'novel-review-'));t.after(()=>fs.rmSync(w,{recursive:true,force:true}));const root=initialize(w,'test-novel','Test');const c=read(inside(root,'system/series.json'));c.pov_character='hero';atomic(inside(root,'system/series.json'),c);const s=read(inside(root,'state.json'));s.cards=[{id:'hero',type:'character',name:'Hero',status:'confirmed',source:'test',knows:['a known fact']},{id:'secret',type:'fact',status:'confirmed',source:'test',value:'AUTHOR_SECRET'}];s.current_scene='S1';s.scene_log=[{id:'S1',path:'manuscript/s1.md',status:'draft',source:'test'}];atomic(inside(root,'state.json'),s);fs.writeFileSync(inside(root,'manuscript/s1.md'),'# Test\nA manuscript with FUTURE_SECRET.\n');return root;}
function input(root){const i={series_id:'test-novel',scene_id:'S1',base:fingerprint(root)};return {...i,manuscript_sha256:manuscriptForReview(root,i).sha256,agenda:'AGENDA_SECRET',workflow:'hybrid'};}
test('read and six-perspective review preserve paused canon and isolate character knowledge',t=>{const r=fixture(t),i=input(r),before=fingerprint(r),m=manuscriptCouncil(r,i);assert.equal(m.requests.length,6);assert.equal(m.kind,'manuscript_review');assert.equal(m.execution_mode,'requests_only');assert.equal(m.manuscript.text,fs.readFileSync(inside(r,'manuscript/s1.md'),'utf8'));const pov=m.requests.find(x=>x.role==='character');const serialized=JSON.stringify(pov);for(const secret of ['AUTHOR_SECRET','FUTURE_SECRET','AGENDA_SECRET'])assert.ok(!serialized.includes(secret));assert.ok(serialized.includes('a known fact'));assert.ok(m.requests.find(x=>x.role==='editor').context.manuscript.text.includes('FUTURE_SECRET'));assert.equal(fingerprint(r),before);assert.throws(()=>request(r,'writer','write'),/paused/);});
test('review requires correct series scene exact text workflow and configured character',t=>{const r=fixture(t),i=input(r);for(const edit of [{series_id:'other'},{scene_id:'missing'},{base:'old'},{manuscript_sha256:'wrong'},{agenda:''},{workflow:'unknown'}])assert.throws(()=>manuscriptCouncil(r,{...i,...edit}));const c=read(inside(r,'system/series.json'));c.pov_character=null;atomic(inside(r,'system/series.json'),c);assert.throws(()=>manuscriptCouncil(r,input(r)),/POV/);assert.equal(fs.existsSync(inside(r,'system/councils')),false);});
test('all replies remain proposals and manuscript changes invalidate older review',t=>{const r=fixture(t),m=manuscriptCouncil(r,input(r)),base=fingerprint(r),replies=m.requests.map(q=>({...q,output:'Review only'})),resolution={execution_mode:'conversation_single_assistant',summary:'Consider changes',objections:[],pending:['User decision']};assert.throws(()=>finishCouncil(r,m.id,replies.slice(1),resolution));assert.equal(finishCouncil(r,m.id,replies,resolution).status,'reviewed_proposal');assert.equal(finishCouncil(r,m.id,replies,resolution).status,'reviewed_proposal');assert.equal(fingerprint(r),base);fs.appendFileSync(inside(r,'manuscript/s1.md'),'Later edit');assert.throws(()=>finishCouncil(r,m.id,replies,resolution),/stale/);assert.equal(read(inside(r,'system/control.json')).manuscript_generation_enabled,false);});
test('six mock workers collect original review requests without exposing author text to character',async t=>{const r=fixture(t),c=read(inside(r,'system/series.json'));const script="let s='';process.stdin.on('data',x=>s+=x);process.stdin.on('end',()=>{const q=JSON.parse(s);if(q.role==='character'&&/AUTHOR_SECRET|FUTURE_SECRET|AGENDA_SECRET/.test(s))process.exit(2);console.log(JSON.stringify({request_id:q.request_id,series_id:q.series_id,base:q.base,role:q.role,output:'MOCK review'}));});";for(const role of ['socrates','machiavelli','keynes','editor','continuity','character'])c.workers[role]={command:process.execPath,args:['-e',script],timeout_ms:5000};atomic(inside(r,'system/series.json'),c);const m=manuscriptCouncil(r,input(r)),base=fingerprint(r);for(const q of m.requests)assert.equal((await runCouncilReview(r,m.id,q.role)).status,'received');const collected=councilReplies(r,m.id);assert.equal(collected.replies.length,6);assert.equal(collected.ready_for_resolution,true);assert.equal((await runCouncilReview(r,m.id,'character')).status,'already_received');assert.equal(finishCouncil(r,m.id,collected.replies,{execution_mode:'external_workers',summary:'Mock only',objections:[],pending:['Real AI untested']}).status,'reviewed_proposal');assert.equal(fingerprint(r),base);});
