import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import vm from 'node:vm';
import {planningServer} from './planning-server.mjs';
import {initialize,finishCouncil} from './project.mjs';
import {read,atomic,inside,fingerprint,hash} from './engine.mjs';
import {manuscriptCouncil} from './manuscript-review.mjs';
import {saveReviewDecisions,readReviewDecisions,reviewDecisionHistory} from './review-decisions.mjs';
test('HTTP history authenticates, serves read-only display and refuses unknown or active meetings',async t=>{
  const {r,m,input}=setup(t),base=fingerprint(r);saveReviewDecisions(r,input);
  const server=planningServer(r);await new Promise(done=>server.listen(0,'127.0.0.1',done));t.after(async()=>{server.closeAllConnections();await new Promise(done=>server.close(done));});
  const url='http://127.0.0.1:'+server.address().port,ctx=await(await fetch(url+'/api/init')).json(),headers={'X-Planning-Token':ctx.token},route='/api/decision-history?meeting='+m.id;
  assert.equal((await fetch(url+route)).status,403);assert.equal((await fetch(url+route,{headers:{...headers,Origin:'https://other.example'}})).status,403);
  const response=await fetch(url+route,{headers});assert.equal(response.status,200);assert.equal((await response.json()).records.length,1);assert.equal(response.headers.get('cache-control'),'no-store');
  assert.equal((await fetch(url+'/api/decision-history?meeting='+crypto.randomUUID(),{headers})).status,409);
  const page=await(await fetch(url+'/decision-history?meeting='+m.id)).text();new vm.Script(page.match(/<script>([\s\S]*?)<\/script>/)[1]);assert.ok(page.includes('p.textContent=value'));assert.ok(!page.includes('innerHTML'));assert.ok((await(await fetch(url+'/')).text()).includes('/decision-history?meeting='));assert.equal(fingerprint(r),base);
  atomic(inside(r,'system/transaction-active.json'),{});assert.equal((await fetch(url+route,{headers})).status,409);
});
test('history is read-only, separates meetings and hides invalid payloads without choosing a latest decision',t=>{
  const {r,m,input}=setup(t),before=fingerprint(r);
  assert.deepEqual(reviewDecisionHistory(r,m.id).records,[]);
  assert.equal(fs.existsSync(inside(r,'system/review-decisions')),false);
  saveReviewDecisions(r,input);
  saveReviewDecisions(r,{...input,operation_id:crypto.randomUUID(),issues:[{...input.issues[0],decision:'accept'}]});
  let h=reviewDecisionHistory(r,m.id);assert.equal(h.records.length,2);assert.equal(h.issues.length,0);
  assert.deepEqual(h.records.map(x=>x.issues[0].decision).sort(),['accept','defer']);
  const other=manuscriptCouncil(r,{series_id:'example',scene_id:'S1',base:before,manuscript_sha256:m.manuscript.sha256,agenda:'Other',workflow:'conversation'});
  finishCouncil(r,other.id,other.requests.map(q=>({...q,output:'review'})),{execution_mode:'conversation_single_assistant',summary:'proposal',objections:[],pending:[]});
  saveReviewDecisions(r,{...input,meeting_id:other.id,operation_id:crypto.randomUUID()});
  assert.equal(reviewDecisionHistory(r,m.id).records.length,2);
  const bad=crypto.randomUUID();atomic(inside(r,'system/review-decisions/'+bad+'.json'),{meeting_id:m.id,comment:'UNTRUSTED_CONTENT'});
  h=reviewDecisionHistory(r,m.id);assert.equal(h.records.length,2);assert.equal(h.issues.length,1);assert.ok(!JSON.stringify(h).includes('UNTRUSTED_CONTENT'));assert.equal(fingerprint(r),before);
  fs.appendFileSync(inside(r,'manuscript/one.md'),'変更');assert.equal(reviewDecisionHistory(r,m.id).stale,true);
  atomic(inside(r,'system/transaction-active.json'),{});assert.throws(()=>reviewDecisionHistory(r,m.id),/unfinished transaction/);
});
test('a valid record copied to another operation filename is rejected',t=>{
  const {r,m,input}=setup(t);saveReviewDecisions(r,input);
  const other=crypto.randomUUID();
  fs.copyFileSync(inside(r,'system/review-decisions/'+input.operation_id+'.json'),inside(r,'system/review-decisions/'+other+'.json'));
  assert.throws(()=>readReviewDecisions(r,m.id,other),/mismatch/);
  assert.throws(()=>saveReviewDecisions(r,{...input,operation_id:other}),/mismatch/);
  const original=readReviewDecisions(r,m.id,input.operation_id);
  assert.equal(original.operation_id,input.operation_id);
  const file=inside(r,'system/review-decisions/'+input.operation_id+'.json');
  atomic(file,{...original,schema_version:999});
  assert.throws(()=>readReviewDecisions(r,m.id,input.operation_id),/mismatch/);
});
function setup(t){
  const w=fs.mkdtempSync(path.join(os.tmpdir(),'review-decisions-'));t.after(()=>fs.rmSync(w,{recursive:true,force:true}));
  const r=initialize(w,'example','Example');const c=read(inside(r,'system/series.json'));c.pov_character='hero';atomic(inside(r,'system/series.json'),c);
  const s=read(inside(r,'state.json'));s.cards=[{id:'hero',type:'character',name:'Hero',knows:[],status:'confirmed',source:'test'}];s.scene_log=[{id:'S1',path:'manuscript/one.md',status:'draft',source:'test'}];atomic(inside(r,'state.json'),s);
  const body='雨が降る。\n雨が降る。';fs.writeFileSync(inside(r,'manuscript/one.md'),body);
  const m=manuscriptCouncil(r,{series_id:'example',scene_id:'S1',base:fingerprint(r),manuscript_sha256:hash(body),agenda:'Review',workflow:'conversation'});
  finishCouncil(r,m.id,m.requests.map(q=>({...q,output:'review'})),{execution_mode:'conversation_single_assistant',summary:'proposal',objections:[],pending:[]});
  const input={operation_id:crypto.randomUUID(),meeting_id:m.id,series_id:m.series_id,base:m.base,manuscript_sha256:m.manuscript.sha256,issues:[{id:'I1',role:'editor',anchor:{start:6,end:11,quote:'雨が降る。'},comment:'反復の意図',decision:'defer',reason:'作者の判断を待つ',actor:'test user',source:'test instruction'}]};return {r,m,input};
}
test('decisions anchor repeated text exactly, replay and preserve paused canon',t=>{const {r,m,input}=setup(t),before=fingerprint(r);const a=saveReviewDecisions(r,input);assert.equal(a.issues[0].anchor.start,6);assert.deepEqual(saveReviewDecisions(r,input),a);assert.equal(fingerprint(r),before);assert.equal(read(inside(r,'system/control.json')).manuscript_generation_enabled,false);assert.throws(()=>saveReviewDecisions(r,{...input,issues:[{...input.issues[0],decision:'accept'}]}),/differently/);assert.equal(readReviewDecisions(r,m.id,input.operation_id).stale,false);});
test('reject mismatched anchors, identity and missing decision evidence before writing',t=>{const {r,input}=setup(t);for(const bad of [{...input,series_id:'foreign'},{...input,manuscript_sha256:'bad'},{...input,issues:[{...input.issues[0],reason:''}]},{...input,issues:[{...input.issues[0],role:'unknown'}]},{...input,issues:[{...input.issues[0],anchor:{start:0,end:3,quote:'wrong'}}]},{...input,issues:[input.issues[0],input.issues[0]]}])assert.throws(()=>saveReviewDecisions(r,bad));assert.equal(fs.existsSync(inside(r,'system/review-decisions')),false);});
test('old records remain readable as stale; new saves and corrupted records are refused',t=>{const {r,m,input}=setup(t);saveReviewDecisions(r,input);fs.appendFileSync(inside(r,'manuscript/one.md'),'変更');assert.equal(readReviewDecisions(r,m.id,input.operation_id).stale,true);assert.throws(()=>saveReviewDecisions(r,{...input,operation_id:crypto.randomUUID()}),/stale/);const p=inside(r,'system/review-decisions/'+input.operation_id+'.json'),v=read(p);v.issues[0].decision='accept';atomic(p,v);assert.throws(()=>readReviewDecisions(r,m.id,input.operation_id),/mismatch/);});
