import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {initialize} from './project.mjs';
import {read,atomic,inside} from './engine.mjs';
import {prepareSync,sendSync,reconcileSync,syncStatus} from './sync.mjs';
function setup(t){const w=fs.mkdtempSync(path.join(os.tmpdir(),'novel-sync-'));t.after(()=>fs.rmSync(w,{recursive:true,force:true}));const root=initialize(w,'sync-test','test'),p=inside(root,'system/series.json'),c=read(p);c.sync_files=['state.json'];c.destinations={test:{space:'fixture'}};atomic(p,c);let writes=0;const data=new Map([['existing',{content:'before',version:'v1'}]]),ops=new Map();const adapter={destination:'test',destination_config:c.destinations.test,conditional_update:true,idempotent_create:true,read:async id=>data.get(id),lookup:async id=>ops.has(id)?[ops.get(id)]:[],write:async r=>{writes++;if(r.target&&data.get(r.target)?.version!==r.expected_version)throw Error('version conflict');const target=r.target??'new-page';data.set(target,{content:r.content,version:'v2'});ops.set(r.operation_id,target);return {target};}};return {root,adapter,data,ops,writes:()=>writes};}
test('update verifies content and repeated send does not write again',async t=>{const f=setup(t),r=await prepareSync(f.root,{source:'state.json',destination:'test',target:'existing',expected_version:'v1'});assert.equal((await sendSync(f.root,r.id,f.adapter)).status,'verified');await sendSync(f.root,r.id,f.adapter);assert.equal(f.writes(),1);});
test('remote edit is preserved',async t=>{const f=setup(t),r=await prepareSync(f.root,{source:'state.json',destination:'test',target:'existing',expected_version:'v1'});f.data.set('existing',{content:'external edit',version:'v9'});assert.equal((await sendSync(f.root,r.id,f.adapter)).status,'conflict');assert.equal(f.writes(),0);});
test('lost create response reconciles without duplicate creation',async t=>{const f=setup(t),r=await prepareSync(f.root,{source:'state.json',destination:'test'}),write=f.adapter.write;f.adapter.write=async req=>{await write(req);throw Error('connection lost');};assert.equal((await sendSync(f.root,r.id,f.adapter)).status,'uncertain');await assert.rejects(sendSync(f.root,r.id,f.adapter),/reconciliation/);assert.equal((await reconcileSync(f.root,r.id,f.adapter)).status,'verified');assert.equal(f.writes(),1);});
test('unlocated create stays uncertain without retry',async t=>{const f=setup(t),r=await prepareSync(f.root,{source:'state.json',destination:'test'});f.adapter.write=async()=>{throw Error('offline');};await sendSync(f.root,r.id,f.adapter);assert.equal((await reconcileSync(f.root,r.id,f.adapter)).status,'uncertain');assert.equal(f.writes(),0);});
test('local edit invalidates prepared plan',async t=>{const f=setup(t),r=await prepareSync(f.root,{source:'state.json',destination:'test'}),p=inside(f.root,'state.json'),s=read(p);s.next='changed';atomic(p,s);await assert.rejects(sendSync(f.root,r.id,f.adapter),/local source/);assert.equal(f.writes(),0);});
test('unregistered source and wrong destination rejected',async t=>{const f=setup(t);await assert.rejects(prepareSync(f.root,{source:'../other',destination:'test'}),/enabled/);const r=await prepareSync(f.root,{source:'state.json',destination:'test'});await assert.rejects(sendSync(f.root,r.id,{...f.adapter,destination:'other'}),/destination/);});
test('readback failure can be reconciled',async t=>{const f=setup(t),r=await prepareSync(f.root,{source:'state.json',destination:'test'}),readRemote=f.adapter.read;f.adapter.read=async()=>{throw Error('offline');};assert.equal((await sendSync(f.root,r.id,f.adapter)).status,'uncertain');f.adapter.read=readRemote;assert.equal((await reconcileSync(f.root,r.id,f.adapter)).status,'verified');});
test('adapter without required guarantees cannot write',async t=>{const f=setup(t),r=await prepareSync(f.root,{source:'state.json',destination:'test'});f.adapter.idempotent_create=false;await assert.rejects(sendSync(f.root,r.id,f.adapter),/idempotent/);assert.equal(syncStatus(f.root,r.id).attempts,0);});
