import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {workspaceServer} from './workspace-server.mjs';
import {read,inside} from './engine.mjs';
async function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'writing-workspace-')),server=workspaceServer(root);await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const init=await(await fetch(url+'/api/init')).json();t.after(async()=>{await server.closePlanning();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});});return {root,url,token:init.token,post:(route,input,headers={})=>fetch(url+route,{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':init.token,...headers},body:JSON.stringify(input)})};}
test('create two isolated paused series and open the selected planning context',async t=>{const f=await fixture(t);for(const id of ['novel-a','novel-b'])assert.equal((await f.post('/api/create',{id,title:id})).status,201);const list=await(await fetch(f.url+'/api/init')).json();assert.equal(list.series.length,2);assert.equal(read(inside(f.root,'novel-a/system/control.json')).manuscript_generation_enabled,false);assert.deepEqual(read(inside(f.root,'novel-b/state.json')).cards,[]);const a=await(await f.post('/api/open',{id:'novel-a'})).json(),b=await(await f.post('/api/open',{id:'novel-b'})).json();assert.notEqual(a.url,b.url);const context=await(await fetch(a.url+'/api/init')).json();assert.equal(context.series_id,'novel-a');const saved=await fetch(a.url+'/api/save',{method:'POST',headers:{'Content-Type':'application/json','X-Planning-Token':context.token},body:JSON.stringify({operation_id:crypto.randomUUID(),base:context.base,brief:{series_id:'novel-b'}})});assert.equal(saved.status,400);assert.equal((await(await f.post('/api/open',{id:'novel-a'})).json()).url,a.url);});
test('duplicate submissions cannot overwrite existing folders, and reserved paths stay untouched',async t=>{const f=await fixture(t);fs.mkdirSync(path.join(f.root,'sources'));fs.writeFileSync(path.join(f.root,'sources/keep.txt'),'unchanged');const results=await Promise.all([f.post('/api/create',{id:'novel-a',title:'First'}),f.post('/api/create',{id:'novel-a',title:'Second'})]);assert.deepEqual(results.map(r=>r.status).sort(),[201,400]);const title=read(inside(f.root,'novel-a/system/series.json')).title;assert.ok(['First','Second'].includes(title));for(const id of ['../escape','sources','writing-system','amelia'])assert.equal((await f.post('/api/create',{id,title:'No'})).status,400);assert.equal(fs.readFileSync(path.join(f.root,'sources/keep.txt'),'utf8'),'unchanged');});
test('reject cross-origin and unauthenticated mutations; report inconsistent series',async t=>{const f=await fixture(t);assert.equal((await f.post('/api/create',{id:'novel-a',title:'A'},{Origin:'https://example.com'})).status,403);assert.equal((await f.post('/api/create',{id:'novel-a',title:'A'},{'X-Workspace-Token':'wrong'})).status,403);await f.post('/api/create',{id:'novel-a',title:'A'});const file=inside(f.root,'novel-a/system/series.json'),config=read(file);config.series_id='other';fs.writeFileSync(file,JSON.stringify(config));const list=await(await fetch(f.url+'/api/init')).json();assert.equal(list.series.length,0);assert.deepEqual(list.issues,['novel-a']);assert.equal((await f.post('/api/open',{id:'novel-a'})).status,400);});
