import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import {initialize,council,finishCouncil} from './project.mjs';
import {fingerprint,read,hash} from './engine.mjs';
import {proposeWorldEntries} from './world-entries.mjs';
import {readWorldCandidate,worldCandidates} from './world-candidates.mjs';
import {approveTransaction,recoverTransaction} from './transactions.mjs';
import {planningServer} from './planning-server.mjs';
function fixture(t){const w=fs.mkdtempSync(path.join(os.tmpdir(),'world-candidate-')),root=initialize(w,'candidate-test','Test');t.after(()=>fs.rmSync(w,{recursive:true,force:true}));const m=council(root,'test-only council');finishCouncil(root,m.id,m.requests.map(r=>({...r,output:'test-only reply'})),{execution_mode:'conversation_single_assistant',summary:'test review',objections:[],pending:[]});const {transaction}=proposeWorldEntries(root,{series_id:'candidate-test',base:fingerprint(root),meeting_id:m.id,reason:'test-only change',entries:[{category:'countries',id:'test-country',value:'test value',status:'proposal',sources:['test-only source']}]});return {root,id:transaction.id,file:path.join(root,'system/transactions',transaction.id,'record.json')};}
test('candidate readback separates proposal, approval, apply and rollback without mutating on reads',t=>{const f=fixture(t),before=fingerprint(f.root);let r=readWorldCandidate(f.root,f.id);assert.equal(r.status,'proposed');assert.equal(r.current_matches_before,true);assert.equal(fingerprint(f.root),before);approveTransaction(f.root,f.id,{actor:'tester',source:'test approval'});assert.equal(readWorldCandidate(f.root,f.id).approval.actor,'tester');recoverTransaction(f.root,f.id);r=readWorldCandidate(f.root,f.id);assert.equal(r.status,'applied');assert.equal(r.current_matches_after,true);assert.equal(r.stale,true);recoverTransaction(f.root,f.id,'rollback',{actor:'tester',source:'test cancellation'});r=readWorldCandidate(f.root,f.id);assert.equal(r.status,'rolled_back');assert.equal(r.current_matches_before,true);assert.equal(fingerprint(f.root),before);});
test('candidate history rejects altered, foreign and out-of-scope state payloads',t=>{const f=fixture(t),original=read(f.file);for(const alter of [r=>r.payload.reason='changed',r=>{r.payload.series_id='foreign';r.digest=hash(JSON.stringify(r.payload));},r=>{const e=r.payload.entries.find(e=>e.path==='state.json'),s=JSON.parse(e.after);s.next='unrelated hidden edit';e.after=JSON.stringify(s);r.digest=hash(JSON.stringify(r.payload));}]){const r=structuredClone(original);alter(r);fs.writeFileSync(f.file,JSON.stringify(r));assert.throws(()=>readWorldCandidate(f.root,f.id));assert.equal(worldCandidates(f.root).records.length,0);assert.equal(worldCandidates(f.root).issues.length,1);}});
test('candidate HTTP requires token, stays read-only and survives active transaction read guard',async t=>{const f=fixture(t),server=planningServer(f.root);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));});const url='http://127.0.0.1:'+server.address().port,init=await(await fetch(url+'/api/init')).json(),options={headers:{'X-Planning-Token':init.token}},before=fingerprint(f.root);assert.equal((await fetch(url+'/api/world-candidates')).status,403);const data=await(await fetch(url+'/api/world-candidates',options)).json();assert.equal(data.records[0].id,f.id);assert.equal(fingerprint(f.root),before);const page=await(await fetch(url+'/world-candidates')).text();new vm.Script(page.match(/<script>([\s\S]*?)<\/script>/)[1]);assert.match(await(await fetch(url+'/world-entries')).text(),/href="\/world-candidates"/);const marker=path.join(f.root,'system/transaction-active.json');fs.writeFileSync(marker,JSON.stringify({id:f.id}));assert.equal((await fetch(url+'/api/init')).status,409);assert.equal((await fetch(url+'/api/world-candidates',options)).status,409);fs.unlinkSync(marker);assert.equal((await fetch(url+'/api/init')).status,200);});
