import {chromium} from 'playwright';
import {createServer,preview} from 'vite';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('test-results',{recursive:true});
const server=await createServer({server:{host:'127.0.0.1',port:5180},define:{'import.meta.env.VITE_E2E':'"1"'}});await server.listen();
let browser,production;
try{
 browser=await chromium.launch({args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const click=async(x,y)=>{const b=await page.locator('canvas').boundingBox();await page.mouse.click(b.x+x*b.width/480,b.y+y*b.height/800);};
 await page.goto('http://127.0.0.1:5180');await page.waitForFunction(()=>window.__GDA__?.scene.isActive('Title'));await page.screenshot({path:'test-results/title-mobile.png'});
 await click(240,390);await page.locator('input').fill('リオ');await click(240,560);await page.waitForFunction(()=>window.__GDA__.scene.isActive('Game'));await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>window.__GDA__.scene.getScene('Game').state.name),'リオ');await page.screenshot({path:'test-results/game-mobile.png'});
 const initial=await page.evaluate(()=>window.__GDA__.scene.getScene('Game').state.turn);await click(74,666);await page.waitForFunction(n=>window.__GDA__.scene.getScene('Game').state.turn===n+1,initial);
 await page.reload();await page.waitForFunction(()=>window.__GDA__?.scene.isActive('Title'));await click(240,470);await page.waitForFunction(()=>window.__GDA__.scene.isActive('Game'));assert.equal(await page.evaluate(()=>window.__GDA__.scene.getScene('Game').state.turn),initial+1);
 // A durable encounter fixture isolates animation completion from random map layout.
 await page.evaluate(()=>{const g=window.__GDA__.scene.getScene('Game');const e=g.enemies[0];const pos=[[1,0],[-1,0],[0,1],[0,-1]].find(([dx,dy])=>g.tiles[g.player.y+dy]?.[g.player.x+dx]===0);e.x=g.player.x+pos[0];e.y=g.player.y+pos[1];e.hp=200;e.maxHP=200;g.enemies=[e];g.state.mp=30;g.state.hp=24;g.visible=g.fov.compute(g.player.x,g.player.y);g.redraw();});
 await click(330,686);await page.waitForFunction(()=>!window.__GDA__.scene.getScene('Game').turns.locked,{timeout:5000});
 const cast=await page.evaluate(()=>{const g=window.__GDA__.scene.getScene('Game');return{mp:g.state.mp,hp:g.enemies[0].hp,turn:g.state.turn};});assert.ok(cast.mp<30);assert.ok(cast.hp<200);assert.equal(cast.turn,initial+2);
 await click(422,744);await page.waitForFunction(()=>!window.__GDA__.scene.getScene('Game').turns.locked);assert.equal(await page.evaluate(()=>window.__GDA__.scene.getScene('Game').state.robe),'azure');
 await page.evaluate(()=>{const g=window.__GDA__.scene.getScene('Game');g.enemies[0].hp=0;g.saveGame(false);});const snapshot=await page.evaluate(()=>JSON.parse(localStorage.getItem('gda-save-v1')).snapshot);
 await page.reload();await page.waitForFunction(()=>window.__GDA__?.scene.isActive('Title'));await click(240,470);await page.waitForFunction(()=>window.__GDA__.scene.isActive('Game'));assert.deepEqual(await page.evaluate(()=>window.__GDA__.scene.getScene('Game').state.snapshot),snapshot);
 await page.evaluate(()=>window.__GDA__.scene.getScene('Game').nextFloor());assert.equal(await page.evaluate(()=>window.__GDA__.scene.getScene('Game').state.floor),2);await page.screenshot({path:'test-results/library-mobile.png'});await page.evaluate(()=>window.__GDA__.scene.getScene('Game').nextFloor());assert.equal(await page.evaluate(()=>window.__GDA__.scene.getScene('Game').state.status),'victory');
 await page.screenshot({path:'test-results/victory-mobile.png'});assert.deepEqual(errors,[]);await context.close();
 production=await preview({preview:{host:'127.0.0.1',port:4180}});const offline=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const op=await offline.newPage(),oe=[];op.on('pageerror',e=>oe.push(e.message));await op.goto('http://127.0.0.1:4180');await op.locator('canvas').waitFor();await op.waitForTimeout(1000);const b=await op.locator('canvas').boundingBox();const tap=(x,y)=>op.mouse.click(b.x+x*b.width/480,b.y+y*b.height/800);
 await tap(240,390);await op.locator('input').fill('オフライン');await tap(240,560);await op.waitForFunction(()=>localStorage.getItem('gda-save-v1'));await op.evaluate(()=>navigator.serviceWorker.ready);await op.waitForFunction(()=>navigator.serviceWorker.controller!==null);await offline.setOffline(true);await op.reload();await op.locator('canvas').waitFor();await op.waitForTimeout(1000);await tap(240,470);await op.waitForTimeout(1800);await tap(74,666);await op.waitForTimeout(150);assert.ok(await op.evaluate(()=>JSON.parse(localStorage.getItem('gda-save-v1')).turn>=1));assert.equal(await op.evaluate(()=>JSON.parse(localStorage.getItem('gda-save-v1')).name),'オフライン');await op.screenshot({path:'test-results/offline-mobile.png'});assert.deepEqual(oe,[]);await offline.close();console.log('PASS: mobile boot, naming, wait, save/resume, finite cast animation, robe switch, defeated-enemy restore, B2F/victory, offline production restart');
}finally{await browser?.close();await server.close();production?.httpServer.close();}
